src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\PaiementRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ReservationRepository;
use App\Service\DateHelper;
use App\Service\TarifsHelper;
use DateTime;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{

    private $tarifsGaranties;
    private $tarifsOptions;

    public function __construct()
    {

        $this->paiements = new ArrayCollection();
        $this->options = new ArrayCollection();
        $this->garanties = new ArrayCollection();
        $this->setReportedFalseValue();
        $this->conducteursClient = new ArrayCollection();
        $this->fraisSupplResas = new ArrayCollection();
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("reserv:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable = true)
     * @Groups("reserv:read")
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     * 
     */
    private $client;

    /**
     * @ORM\Column(type="datetime")
     * 
     */
    private $date_reservation;

    /**
     * @ORM\Column(type="datetime")
     * @Groups("reserv:read")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime")
     * @Groups("reserv:read")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     */
    private $lieu;

    /**
     * @ORM\ManyToOne(targetEntity=Vehicule::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $vehicule;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     */
    private $code_reservation;



    /**
     * @ORM\ManyToOne(targetEntity=ModeReservation::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=true)
     */
    private $mode_reservation;

    /**
     * @ORM\ManyToOne(targetEntity=EtatReservation::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=true)
     */
    private $etat_reservation;

    /**
     * @ORM\OneToMany(targetEntity=Paiement::class, mappedBy="reservation")
     */
    private $paiements;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $agenceDepart;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $agenceRetour;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $numDevis;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $reference;


    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $tarifVehicule;

    /**
     * @ORM\ManyToMany(targetEntity=Options::class, inversedBy="reservations")
     */
    private $options;

    /**
     * @ORM\ManyToMany(targetEntity=Garantie::class, inversedBy="reservations")
     */
    private $garanties;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prixOptions;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prixGaranties;

    /**
     * @ORM\Column(type="string", length=255, nullable = true)
     */
    private $stripeSessionId;

    private $sommePaiements;

    /**
     * @ORM\OneToOne(targetEntity=Avis::class, mappedBy="reservation", cascade={"persist", "remove"})
     * 
     */
    private $avis;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $archived;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $canceled;



    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $conducteur;

    /**
     * @ORM\Column(type="boolean")
     */
    private $reported;

    /**
     * @ORM\ManyToMany(targetEntity=Conducteur::class, inversedBy="reservations")
     */
    private $conducteursClient;

    /**
     * @ORM\OneToMany(targetEntity=FraisSupplResa::class, mappedBy="reservation", orphanRemoval=true)
     */
    private $fraisSupplResas;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getClient(): ?User
    {
        return $this->client;
    }

    public function setClient(?User $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getDateReservation(): ?\DateTimeInterface
    {
        return $this->date_reservation;
    }

    public function setDateReservation(\DateTimeInterface $date_reservation): self
    {
        $this->date_reservation = $date_reservation;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getVehicule(): ?Vehicule
    {
        return $this->vehicule;
    }

    public function setVehicule(?Vehicule $vehicule): self
    {
        $this->vehicule = $vehicule;

        return $this;
    }

    public function getCodeReservation(): ?string
    {
        return $this->code_reservation;
    }

    public function setCodeReservation(string $code_reservation): self
    {
        $this->code_reservation = $code_reservation;

        return $this;
    }

    public function getModeReservation(): ?ModeReservation
    {
        return $this->mode_reservation;
    }

    public function setModeReservation(?ModeReservation $mode_reservation): self
    {
        $this->mode_reservation = $mode_reservation;

        return $this;
    }

    public function getEtatReservation(): ?EtatReservation
    {
        return $this->etat_reservation;
    }

    public function setEtatReservation(?EtatReservation $etat_reservation): self
    {
        $this->etat_reservation = $etat_reservation;

        return $this;
    }


    /**
     * @return Collection|Paiement[]
     */
    public function getPaiements(): Collection
    {
        return $this->paiements;
    }

    public function addPaiement(Paiement $paiement): self
    {
        if (!$this->paiements->contains($paiement)) {
            $this->paiements[] = $paiement;
            $paiement->setReservation($this);
        }

        return $this;
    }

    public function removePaiement(Paiement $paiement): self
    {
        if ($this->paiements->removeElement($paiement)) {
            // set the owning side to null (unless already changed)
            if ($paiement->getReservation() === $this) {
                $paiement->setReservation(null);
            }
        }

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }


    /**
     * toString
     * @return string
     */
    public function __toString()
    {
        return $this->getCodeReservation();
    }

    public function getAgenceDepart(): ?string
    {
        return $this->agenceDepart;
    }

    public function setAgenceDepart(?string $agenceDepart): self
    {
        $this->agenceDepart = $agenceDepart;

        return $this;
    }

    public function getAgenceRetour(): ?string
    {
        return $this->agenceRetour;
    }

    public function setAgenceRetour(?string $agenceRetour): self
    {
        $this->agenceRetour = $agenceRetour;

        return $this;
    }


    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDuree(): ?float
    {
        return $this->duree;
    }

    public function setDuree(?float $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getNumDevis(): ?string
    {
        return $this->numDevis;
    }

    public function setNumDevis(?string $numDevis): self
    {
        $this->numDevis = $numDevis;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    // custom function
    public function setRefRes($pref, $currentID)
    {
        $dateHelper = new DateHelper();
        $currentTime = new \DateTime('NOW');
        $year = $currentTime->format('Y');
        $month = $dateHelper->getMonthName($currentTime);
        if ($currentID < 10) {
            $currentID = '0000' . $currentID;
        }
        if ($currentID < 100 && $currentID > 10) {
            $currentID = '000' . $currentID;
        }
        if ($currentID < 1000 && $currentID > 100) {

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Vehicule;
use App\Entity\Reservation;
use App\Form\FraisSupplResaType;
use Symfony\Component\Form\AbstractType;
use App\Repository\ReservationRepository;
use DateTime;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_debut', DateTimeType::class, [
                'widget' => 'single_text',
                'attr' => [
                    "step" => "any"
                ]
            ])
            ->add('date_fin', DateTimeType::class, [
                'widget' => 'single_text',
                'attr' => [
                    "step" => "any"
                ]
            ])
            // ->add('type')
            // ->add('date_reservation', DateTimeType::class, [
            //     'widget' => 'single_text',
            // ])
            // ->add('lieu')
            // ->add('code_reservation')
            // ->add('client')
            // ->add('mode_reservation')
            // ->add('prix')
            ->add('agenceDepart', ChoiceType::class, [
                'choices'  => [
                    'Aéroport de Point-à-pitre' => 'Aéroport de Point-à-pitre',
                    'Agence du Moule' => 'Agence du Moule',
                    'Gare Maritime de Bergervin' => 'Gare Maritime de Bergervin',
                    'Gare maritime de Saint-François' => 'Gare maritime de Saint-François',
                    'Point de livraison : ' =>
                    [
                        'Abymes' => 'Abymes',
                        'Anse-bertrand' => 'Anse-bertrand',
                        'Gosier' => 'Gosier',
                        'Moule' => 'Moule',
                        "Morne-à-l'Eau" => "Morne-à-l'Eau",
                        "Petit-canal" => "Petit-canal",
                        "Pointe-à-pitre" => "Pointe-à-pitre",
                        "Port-louis" => "Port-louis",
                        "Sainte-anne" => "Sainte-anne",
                        "Saint-François" => "Saint-François",
                    ]
                ],
                'required' => true
            ])
            ->add('agenceRetour', ChoiceType::class, [
                'choices'  => [
                    'Aéroport de Point-à-pitre' => 'Aéroport de Point-à-pitre',
                    'Agence du Moule' => 'Agence du Moule',
                    'Gare Maritime de Bergervin' => 'Gare Maritime de Bergervin',
                    'Gare maritime de Saint-François' => 'Gare maritime de Saint-François',
                    'Point de livraison : ' =>
                    [
                        'Abymes' => 'Abymes',
                        'Anse-bertrand' => 'Anse-bertrand',
                        'Gosier' => 'Gosier',
                        'Moule' => 'Moule',
                        "Morne-à-l'Eau" => "Morne-à-l'Eau",
                        "Petit-canal" => "Petit-canal",
                        "Pointe-à-pitre" => "Pointe-à-pitre",
                        "Port-louis" => "Port-louis",
                        "Sainte-anne" => "Sainte-anne",
                        "Saint-François" => "Saint-François",
                    ]
                ],
                'required' => true
            ])
            ->add('vehicule', HiddenType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

templates/client/reservation/details/details_reservation.html.twig
{% extends 'baseClient.html.twig' %}

{% block title %}Détails reservation
{% endblock %}


{% block stylesheets %}{% endblock %}


{% block body %}

	<div class="x_panel">
		<div class="row">
			<div class="col-md-6">
				<h5>
					<i class="fa fa-folder-open-o"></i>
					RESERVATION -
					{{reservation.reference}}
				</h5>
			</div>
			<div class="col-md-6 text-right">
				<a href="{{path('client_reservations')}}" class="btn btn-dark" title="Liste réservations">
					<i class="fa fa-reply"></i>
					Mes réservations</a>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="x_panel">
				<h6>
					{{reservation.vehicule.marque}}
					{{reservation.vehicule.modele}}</h6>

				<img src="{{vich_uploader_asset(reservation.vehicule, 'imageFile') }}" alt="{{ reservation.vehicule.image }}" class="img-circle  " style="width : 250px;">
			</div>
		</div>
		<div class="col-md-9">
			<div class="x_panel">
				<div class="infosClient">
					<div class="x_title">
						<h4 class="text-uppercase">
							informations client</h4>
					</div>
					<div class="x_content">
						<strong>Nom/Prénom :</strong>
						<span>
							{{reservation.client.nom}}
							{{reservation.client.prenom}}
						</span>
						<br>
						<strong>Téléphone :</strong>
						<span>
							{{reservation.client.telephone}}
						</span>

						<br>
						<strong>Email :</strong>
						<span>
							{{reservation.client.mail}}
						</span>

					</div>

				</div>
			</div>
			<div class="x_panel">
				<div class="conducteurs">
					<div class="x_title">
						<h4 class="text-uppercase">Conducteur(s)</h4>
					</div>

					{# {{dump(reservation)}} #}

					{% if reservation.conducteursClient|length < 2 %}
						<button type="button" class="btn btn-danger " data-toggle="modal" data-target="#modalConducteur">
							<i class="fa  fa-plus"></i>
							Ajouter</button>
					{% endif %}

					<div class="x_content">

						{% set somme = 0  %}
						{% for conducteur in reservation.conducteursClient %}
							{% if conducteur.isPrincipal %}
								{% set somme = somme + 1  %}
							{% endif %}
						{% endfor %}

						{% for conducteur in reservation.conducteursClient %}
							<div class="mb-3 border-blue">
								<div class="row ">
									<div class="col-md-4">{{conducteur.nom}}
										{{conducteur.prenom}}
										<br>
										{% if conducteur.isPrincipal %}
											<span class="badge badge-danger">
												conducteur principal
											</span>
										{% endif %}
									</div>
									<div class="col-md-4">
										<strong>Numéro de permis :
										</strong>
										{{conducteur.numeroPermis}}
										<br>
										<strong>Date de délivrance :
										</strong>
										{{conducteur.dateDelivrance|date('d/m/Y')}}
										<br>
										<strong>Ville de délivrance :
										</strong>
										{{conducteur.villeDelivrance}}
									</div>
									<div class="col-md-1"></div>
									<div class="col-md-3">
										<div class="row">
											{% if somme == 0  %}
												<div class="col-md-4 col-sm-4 col-xs-4 text-right">
													<a href="{{path('make_conducteur_principal', {'id': conducteur.id, 'id_resa': reservation.id})}}" class="btn btn-success" title="Rendre principal">
														<i class="fa fa-check"></i>
													</a>
												</div>
											{% elseif conducteur.isPrincipal %}
												<div class="col-md-4 col-sm-4 col-xs-4 text-right">
													<a href="{{path('remove_conducteur_principal', {'id': conducteur.id, 'id_resa': reservation.id})}}" class="btn btn-dark" title="Rendre non principal">
														<i class="fa fa-edit"></i>
													</a>
												</div>
											{% endif %}
											<div class="col-md-4 col-sm-4 col-xs-4 text-right">
												<a href="{{path('conducteur_edit', {'id': conducteur.id})}}" class="btn btn-warning" title="Modifier">
													<i class="fa fa-reply"></i>
												</a>
											</div>
											<div class="col-md-4 col-sm-4 col-xs-4">
												<form method="post" action="{{ path('client_conducteur_remove_reservation', {'id': conducteur.id, 'id_resa' : reservation.id}) }}" onsubmit="return confirm('Êtes-vous sûre de vouloir supprimer ce conducteur ?');">
													<input type="hidden" name="_method" value="DELETE">
													<input type="hidden" name="reservation" value="{{reservation.id}}">

													<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ conducteur.id) }}">
													<button class="btn btn-danger" title="Supprimer">
														<i class="fa fa-close (alias)" aria-hidden="true"></i>
													</button>
												</form>
											</div>
										</div>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
			<div class="x_panel">
				<div class="periode_location">
					<div class="x_title">
						<h4 class="text-uppercase">période de location</h4>
					</div>
					<div class="row">
						<div class="col-md-6">
							<strong>Départ :
							</strong>
							{{reservation.agenceDepart}}
							<br>
							{{reservation.dateDebut|date('d/m/Y')}}-{{reservation.dateDebut|date('H:i')}}
						</div>
						<div class="col-md-6">
							<strong>Rétour :
							</strong>
							{{reservation.agenceRetour}}
							<br>
							{{reservation.dateFin|date('d/m/Y')}}-{{reservation.dateFin|date('H:i')}}
						</div>
						<div class="col-md-6">
							<strong>Jours de location :
							</strong>
							{{reservation.duree}}
						</div>
						<div class="col-md-6">
							<strong>Nombre de personnes :
							</strong><br>
							<span class="font-italic">Adulte(s) :
							</span>
							{{reservation.client.infosResa ? reservation.client.infosResa.nbrAdultes : "non renseigné" }}
							<br>
							<span class="font-italic">Enfant(s) :
							</span>
							{{reservation.client.infosResa ? reservation.client.infosResa.nbrEnfants : "non renseigné"}}
							<br>
							<span class="font-italic">Bébé(s) :
								{{ reservation.client.infosResa ? reservation.client.infosResa.nbrBebes : "non renseigné"}}
							</span>

						</div>
					</div>
				</div>
			</div>
			<div class="x_panel">
				<div class="options_garanties">
					<div class="x_title">
						<h4 class="text-uppercase">options et garanties souscrites</h4>
					</div>
					<strong>Option(s) souscrite(s) :
					</strong><br>
					<ul>
						{% if reservation.conducteur %}
							<li>Conducteur</li>
						{% endif %}

						{% for option in reservation.options %}
							<li>
								{{option}}</li>
						{% endfor %}
					</ul>
					<strong>Garantie(s) souscrite(s) :
					</strong><br>
					<ul>
						{% for garantie in reservation.garanties %}
							<li>
								{{garantie}}</li>
						{% endfor %}
					</ul>
				</div>
			</div>
			<div class="x_panel">
				<div class="montant_reservation">
					<div class="x_title">
						<div class="row">
							<div class="col-auto pl-2">
								<h2>
									<h4 class="text-uppercase">montant total de la réservation</h4>
								</h2>
							</div>
							<div class="col-auto ml-auto d-flex align-items-center">
								<div class="js-prix">
									{{reservation.prix}}
									€
								</div>
							</div>
						</div>
					</div>
					<div class="x_content ">
						<div class="row">
							<div class="col-md-8 col-sm-8 col-xs-8">
								<i class="fa fa-chevron-right"></i>Location NDMR
								{{ reservation.duree }}
								jours
							</div>
							<div class="col-md-4 col-sm-4 col-xs-4">
								<div class="text-right">
									{{reservation.tarifVehicule}}€
								</div>
							</div>

							<div class="col-md-8 col-sm-8 col-xs-8">
								<i class="fa fa-chevron-right"></i>Total dépassements horaires
							</div>
							<div class="col-md-4 col-sm-4 col-xs-4">
								<div class="text-right">
									0 €
								</div>
							</div>

							<div class="col-md-8 col-sm-8 col-xs-8">
								<i class="fa fa-chevron-right"></i>Total options souscrites
							</div>
							<div class="col-md-4 col-sm-4 col-xs-4">
								<div class="text-right">{{reservation.prixGaranties}}€</div>
							</div>

							<div class="col-md-8 col-sm-8 col-xs-8">
								<i class="fa fa-chevron-right"></i>Total garanties souscrites

							</div>
							<div class="col-md-4 col-sm-4 col-xs-4">
								<div class="text-right">
									{{reservation.prixOptions}}
									€
								</div>
							</div>

							<div class="col-md-8 col-sm-8 col-xs-8">
								<i class="fa fa-chevron-right"></i>Montant de la remise
							</div>
							<div class="col-md-4 col-sm-4 col-xs-4">
								<div class="text-right">
									0 €
								</div>
							</div>

							<div class="col-md-8 col-sm-8 col-xs-8">
								<i class="fa fa-chevron-right"></i>Montant à régler
							</div>
							<div class="col-md-4 col-sm-4 col-xs-4">
								<div class="text-right">
									{{reservation.prix}}
									€
								</div>
							</div>


						</div>

					</div>
				</div>
			</div>
			<div class="x_panel">
				<div class="reglement">
					<div class="x_title">
						<h4 class="text-uppercase">réglement</h4>
					</div>
					<div class="x_content">
						{% for paiement in reservation.paiements %}
							<table class="table-bordered w-100 bg-dark">
								<tr>
									<td>
										{{paiement.datePaiement|date('d/m/Y H:i')}}
									</td>
									<td class="text-center">
										{{paiement.modePaiement.libelle}}
									</td>
									<td class="text-right">
										{{paiement.montant}}€
									</td>
								</tr>
							</table>

						{% endfor %}
						<div class="row">
							<div class="col-md-6">-Total payé</div>
							<div class="col-md-6 text-right">{{reservation.sommePaiements}}€</div>
							<br>
							<div class="col-md-6">-Solde</div>
							<div class="col-md-6 text-right">{{reservation.prix - reservation.sommePaiements}}€</div>
						</div>
					</div>
					<div class="text-right">
						{% if reservation.prix > reservation.sommePaiements %}
							<form action="{{ path('paiement_sold') }}" method="POST">
								<input type="hidden" name="montantSolde" value="{{ reservation.prix - reservation.sommePaiements }}">
								<input type="hidden" name="reservation" value="{{ reservation.id }}">
								<button class="btn btn-danger">Payer solde
									{{ reservation.prix - reservation.sommePaiements }}€
								</button>
							</form>
						{% endif %}
					</div>
				</div>
			</div>

		</div>
	</div>

	{% include "client/reservation/modalConducteur.html.twig" %}

{% endblock %}
{% block javascripts %}
	<!-- Datatables -->
	<script src="../../admin/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
	<script src="../../admin/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
	<script src="../../admin/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
	<script src="../../admin/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
	<script src="../../admin/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
	<script src="../../admin/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
	<script src="../../admin/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
	<script src="../../admin/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
	<script src="../../admin/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
	<script src="../../admin/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
	<script src="../../admin/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
	<script src="../../admin/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
	<script src="../../admin/vendors/jszip/dist/jszip.min.js"></script>
	<script src="../../admin/vendors/pdfmake/build/pdfmake.min.js"></script>
	<script src="../../admin/vendors/pdfmake/build/vfs_fonts.js"></script>
	<script src="../../js/admin/jspdf.min.js"></script>
	<script src="../../js/admin/jspdf.plugin.autotable.js"></script>
	<script src="../../js/admin/factureJsPDF.js"></script>
{% endblock  %}

templates/client/reservation/details/form_add_conducteur.html.twig
{% if avalaibleDrivers|length > 0 %}
    <form action="{{ path('client_add_conducteur', {'id': reservation.id}) }}" method="POST">
        <div class="modal-body">
            <label>Sélectionner un conducteur à ajouter à la réservation :</label>
            <select id="monselect" class="form-control" name="conducteur">
                {% for conducteur in avalaibleDrivers %}
                    <option value="{{ conducteur.id }}">{{ conducteur.nom }}
                        {{ conducteur.prenom }}</option>
                {% endfor %}
            </select>
            Le conducteur recherché n'est pas dans la liste ci-desssus?
            <a href="{{ path('client_newConducteur') }}">Cliquez-ici</a>
        </div>
        <div class="modal-footer">
            <button class="btn btn-dark" data-dismiss="modal">
                <i class="fa fa-close"></i>
                Annuler
            </button>
            <button class="btn btn-danger" type="submit">
                <i class="fa fa-save"></i>
                Valider
            </button>
        </div>
    </form>
{% else %}
    <div class="p-3 text-center">
        <a href="{{ path('client_newConducteur') }}">Créer un nouveau conducteur</a>
    </div>
{% endif %}